Unittesting helper.py and enum.py
zhinst/labone-python pull request #25
Opened 2023-11-13 12:52 UTC by rayklauck

Reused some of the old tests

2023-11-14 07:05 UTC, tobiasah requested changes
🌞 next time, clean up your commit messages before requesting a review

2023-11-15 17:28 UTC, rayklauck commented on tests/nodetree/test_entry_point.py
> +    ) as new_mock, patch(
I am not sure in which manner one could do this here

2023-11-15 17:38 UTC, rayklauck commented on tests/nodetree/test_enum.py
> +    parsed = parser(
There is no warning thrown and checking it lets the test fail. Is logger.warning really throwing a warning and not just logging one?

2023-11-16 16:30 UTC, tobiasah commented on tests/nodetree/test_enum.py
> +    parsed = parser(
ok than never mind

2023-11-16 16:32 UTC, tobiasah approved these changes

2023-11-16 17:46 UTC, merged