Redesign result nodes.
zhinst/labone-python pull request #43
Opened 2023-12-18 08:31 UTC by rayklauck

The former way of using wildcard get results prooved to be not very intuitive. Also result nodes should work consistently through wildcards and and partial nodes. This is now ensured.

Through these refactorings, some logic became obsolete, including the path aliasing and redirecting. This was therefore removed.

2023-12-20 13:06 UTC, YakBizzarro commented
I found a small bug with wildcards, the result match too much. For example
```
res = await devpqsc.zsyncs["*"].connection.status()
res.zsyncs[1]
```
returns
```
ResultNode('/dev10056/zsyncs/1', time: #7889195, data: {'/dev10056/zsyncs/1/connection/status': </dev10056/zsyncs/1/connection/status.Connected: 2>, '/dev10056/zsyncs/10/connection/status': </dev10056/zsyncs/10/connection/status.No connection: 0>, '/dev10056/zsyncs/11/connection/status': </dev10056/zsyncs/11/connection/status.No connection: 0>, '/dev10056/zsyncs/12/connection/status': </dev10056/zsyncs/12/connection/status.No connection: 0>, '/dev10056/zsyncs/13/connection/status': </dev10056/zsyncs/13/connection/status.No connection: 0>, '/dev10056/zsyncs/14/connection/status': </dev10056/zsyncs/14/connection/status.No connection: 0>, '/dev10056/zsyncs/15/connection/status': </dev10056/zsyncs/15/connection/status.No connection: 0>, '/dev10056/zsyncs/16/connection/status': </dev10056/zsyncs/16/connection/status.Connected: 2>, '/dev10056/zsyncs/17/connection/status': </dev10056/zsyncs/17/connection/status.No connection: 0>}) -> ['connection']
```
instead of just
```
ResultNode('/dev10056/zsyncs/1', time: #7889195, data: {'/dev10056/zsyncs/1/connection/status': </dev10056/zsyncs/1/connection/status.Connected: 2>})
```
as expected

2024-01-05 07:31 UTC, tobiasah requested changes
LGTM. There is only one section I do not understand

2024-01-05 12:30 UTC, rayklauck commented on src/labone/nodetree/node.py
> +            raise LabOneInvalidPathError(msg) from e
I am trying to give more useful error messages by differenciating between nodes which 
1. do not exist at all 
2. exist, but are not contained in the result node. 

Does this make sense?

2024-01-05 13:24 UTC, tobiasah approved these changes

2024-01-05 16:32 UTC, merged